name: Build Native Image

on:
  pull_request:
    branches:
      - 'release/*'

jobs:
  native-build:
    runs-on: windows-latest  # required to generate real .exe files

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 21 (GraalVM)
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build native executable
        working-directory: TP-Integrador/server
        run: ./gradlew nativeBuild

      - name: Upload all generated .exe files
        uses: actions/upload-artifact@v4
        with:
          name: native-executables
          path: TP-Integrador/server/build/native/nativeCompile/*.exe
